# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.uiZoneID = QtWidgets.QLineEdit(self.centralwidget)
        self.uiZoneID.setGeometry(QtCore.QRect(10, 40, 161, 20))
        self.uiZoneID.setObjectName("uiZoneID")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.uiZoneAttribute = QtWidgets.QLineEdit(self.centralwidget)
        self.uiZoneAttribute.setGeometry(QtCore.QRect(10, 90, 161, 20))
        self.uiZoneAttribute.setObjectName("uiZoneAttribute")
        self.uiZoneAttributeSP = QtWidgets.QLineEdit(self.centralwidget)
        self.uiZoneAttributeSP.setGeometry(QtCore.QRect(10, 150, 161, 20))
        self.uiZoneAttributeSP.setObjectName("uiZoneAttributeSP")
        self.uiZoneAttributeEX = QtWidgets.QLineEdit(self.centralwidget)
        self.uiZoneAttributeEX.setGeometry(QtCore.QRect(10, 210, 161, 20))
        self.uiZoneAttributeEX.setObjectName("uiZoneAttributeEX")
        self.uiZoneAttributeEXSP = QtWidgets.QLineEdit(self.centralwidget)
        self.uiZoneAttributeEXSP.setGeometry(QtCore.QRect(10, 280, 161, 20))
        self.uiZoneAttributeEXSP.setObjectName("uiZoneAttributeEXSP")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 121, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 175, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 245, 81, 31))
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(60, 330, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(60, 360, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 322, 47, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 47, 31))
        self.label_7.setObjectName("label_7")
        self.uiMap = ClickLabel(self.centralwidget)
        self.uiMap.setGeometry(QtCore.QRect(180, 10, 900, 600))
        self.uiMap.setMinimumSize(QtCore.QSize(900, 600))
        self.uiMap.setFrameShape(QtWidgets.QFrame.Box)
        self.uiMap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.uiMap.setText("")
        self.uiMap.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uiMap.setObjectName("uiMap")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Zone ID"))
        self.label_2.setText(_translate("MainWindow", "Attribute"))
        self.label_3.setText(_translate("MainWindow", "Attribute_sp"))
        self.label_4.setText(_translate("MainWindow", "Attribute_Ex"))
        self.label_5.setText(_translate("MainWindow", "Attribute_Ex_sp"))
        self.label_6.setText(_translate("MainWindow", "Width"))
        self.label_7.setText(_translate("MainWindow", "Height"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad.setText(_translate("MainWindow", "Load..."))
from clicklabel import ClickLabel
